In [2]:
# Smit Thapa
# Problem1
# Question1
import numpy as np
empty_array = np.empty((2,2))
print(empty_array)

[[4.65626569e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [3]:
# Question2
import numpy as np
print(np.ones((4,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
# Question3
import numpy as np
new_array = np.full((2,2), 10, dtype=None)
print(new_array)

[[10 10]
 [10 10]]


In [5]:
# Question4
import numpy as np
given_array = np.ones((2,2))
print(np.zeros_like(given_array))

[[0. 0.]
 [0. 0.]]


In [6]:
# Question5
import numpy as np
given_array = np.zeros((2,2))
print(np.ones_like(given_array))

[[1. 1.]
 [1. 1.]]


In [7]:
# Question6
import numpy as np
new_list = [1,2,3,4]
print(np.array(new_list))

[1 2 3 4]


In [8]:
# Problem2
# Question1
import numpy as np
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
# Question2
import numpy as np
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# Question3
import numpy as np
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# Question4
import numpy as np
array = np.random.random(30)
print(array)
print(array.mean())

[0.01336823 0.68584177 0.09178136 0.1471676  0.03006552 0.71152891
 0.45843019 0.81048042 0.71940001 0.68705851 0.36663727 0.64805516
 0.64187917 0.25710111 0.83299106 0.05687544 0.69513929 0.11603065
 0.53439151 0.44401584 0.81011832 0.12221366 0.30329059 0.10494507
 0.40603523 0.04283907 0.60270814 0.54101937 0.61669805 0.87431454]
0.4457473691691699


In [12]:
# Question5
import numpy as np
array = np.random.random((10,10))
print(np.max(array))
print(np.min(array))

0.9897365519740088
0.02248770291460056


In [13]:
# Question6
import numpy as np
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
# Question7
import numpy as np
array = np.array([1,2,0,0,4,0])
print(np.flip(array))

[0 4 0 0 2 1]


In [15]:
# Question8
import numpy as np
array = np.ones((5,5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
# Question9
import numpy as np
array = np.full((8,8), 0)
array[1::2, ::2] = 1
array[::2, 1::2] = 1
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
# Problem 3
# Question1
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(x + y)
print(v + w)

[[ 6  8]
 [10 13]]
[20 22]


In [18]:
# Question2
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(x - y)
print(v - w)

[[-4 -4]
 [-4 -3]]
[-2 -2]


In [19]:
# Question3
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(x * 2)
print(y * 2)
print(v * 2)
print(w * 2)

[[ 2  4]
 [ 6 10]]
[[10 12]
 [14 16]]
[18 20]
[22 24]


In [20]:
# Question4
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(np.square(x))
print(np.square(y))
print(np.square(v))
print(np.square(w))

[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]


In [21]:
# Question5
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(np.dot(x,y))
print(np.dot(v,w))


[[19 22]
 [50 58]]
219


In [22]:
# Question6
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(np.concatenate((x,y), axis=0))
print(np.concatenate((v.reshape(-1,1),w.reshape(-1,1)), axis=1))

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [29]:
# Question7
import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
error_concat = np.concatenate((x, v))
# we get an error because inorder to concatenate along the rows,
# the number of cloumn must match across the arrays.


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [23]:
# Problem4
# Question1
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
print(np.round(result, decimals=10))

AB = np.dot(A,B)
print(AB)
BA = np.dot(B,A)
print(BA)

ABT = np.transpose(AB)
print(ABT)
AT = np.transpose(A)
BT = np.transpose(B)
BTAT = np.dot(BT, AT)
print(BTAT)

[[1. 0.]
 [0. 1.]]
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [24]:
# Question2
import numpy as np
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])


In [25]:
# Question3
import numpy as np
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
result = np.dot(A_inv, B)
print(result)
# The numpy.linalg module in Numpy provides a powerful suite of linear algebra
# functions that make it easier to perform operations commonly used in 4
# mathematics,and Machine Learning.

[ 2.  1. -2.]
